[tool.poetry]
name = "fastapi-todo"
version = "0.1.0"
description = ""
authors = ["qsmsoft <qsmsoft@gmial.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = {extras = ["standard"], version = "^0.115.8"}
alembic = "^1.14.1"
redis = "^5.2.1"
asyncpg = "^0.30.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
